# Site URL

title: "Foonoo"
url: "http://ekowabaka.me/foonoo"
description: "A PHP based static site geerator"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default

menu:
  - title: Documentation
    url: ./docs/
  - title: Code
    url: https://github.com/foonoo

theme: 
    name: site
    primary-color: "#862020"
    secondary-color: "#ff5912"

plugins:
  - contrib/highlight:
      style: rainbow

assets:
  scss:
    items:
      - scss/homepage.scss:
          priority: -1000

