# Site URL

title: "Foonoo"
url: "http://ekowabaka.me/foonoo"
description: "A PHP based static site generator"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default

theme: 
    name: site
    primary-color: "#4129b3"
    secondary-color: "#ff4b4b"

plugins:
  - foonoo/highlight:
      style: nord

assets:
  scss:
    items:
      - scss/homepage.scss:
          priority: -1000
      - scss/plugins.scss:
          priority: 0

