# Site URL

title: "Foonoo"
url: "http://ekowabaka.me/foonoo"
description: "A PHP based static site generator"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default

theme: 
    name: site
    primary-color: "#4129b3"
    secondary-color: "#ff4b4b"

plugins:
  - foonoo/highlight:
      style: nord
  - foonoo/matomo:
      script: | 
          var _paq = window._paq = window._paq || [];
          /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
            var u="//matomo.fahodzi.com/";
            _paq.push(['setTrackerUrl', u+'matomo.php']);
            _paq.push(['setSiteId', '1']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
          })();
assets:
  scss:
    items:
      - scss/homepage.scss:
          priority: -1000
      - scss/plugins.scss:
          priority: 0

