# Site URL

title: "ClearIce"
url: "http://ekowabaka.me/clearice"
description: "A command line interface tool for PHP"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default

menu:
  - title: Documentation
    url: docs/
  - title: Code
    url: https://github.com/ekowabaka/clearice

theme: 
    name: site
    primary-color: "#1E212B"
    secondary-color: "#4D8B31"

plugins:
  - foonoo/highlight:
      style: rainbow

assets:
  scss:
    items:
      - scss/homepage.scss:
          priority: -1000

