# Site URL

title: "ClearIce"
url: "http://ekowabaka.me/clearice"
description: "A command line interface tool for PHP"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default

menu:
  - title: Documentation
    url: docs/
  - title: Code
    url: https://github.com/ekowabaka/clearice

theme: 
    name: site
    primary-color: "#1E212B"
    secondary-color: "#4D8B31"

plugins:
  - foonoo/highlight:
      style: rainbow
  - foonoo/matomo:
      script: | 
          var _paq = window._paq = window._paq || [];
          /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
            var u="//matomo.fahodzi.com/";
            _paq.push(['setTrackerUrl', u+'matomo.php']);
            _paq.push(['setSiteId', '1']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
          })();

assets:
  scss:
    items:
      - scss/homepage.scss:
          priority: -1000

