title: "ClearICE"
type: default
enable-toc: True
index: Introduction
plugins:
  - contrib/highlight:
      style: rainbow
theme: 
    name: site
    primary-color: "#1E212B"
    secondary-color: "#4D8B31"
