title: "ClearICE"
type: default
enable-toc: True
index: Introduction
plugins:
  - contrib/highlight:
      style: rainbow
theme: 
    name: site
    primary-color: "#bf361a"
    secondary-color: "#e67607"
