name: 'Install Foonoo'
description: 'Install the foonoo static site generator'
runs:
  using: composite
  steps:
    - name: Cloning foonoo dev version
      run: git clone --branch dev https://github.com/foonoo/foonoo /tmp/foonoo
      shell: bash
    - name: Installing composer dependencies
      run: composer install
      shell: bash
      working-directory: /tmp/foonoo
