# Site URL

name: "Ekow Abaka"
url: "http://ekowabaka.me"
description: "Ekow Abaka's personal webpage"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default
assets:
  css: 
    - css/home.css

