# Site URL

title: "Ei: Level Generator Experiments"
url: "http://ekowabaka.me/ei"
description: "Ei!"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default

menu:
  - title: Play
    url: https://ei.ekowabaka.me/play.html?l=3
  - title: Create
    url: https://ei.ekowabaka.me/editor.html

theme: 
    name: site
    primary-color: "#1a1a1a"
    secondary-color: "#ef870b"

plugins:
  - foonoo/responsive_images

assets:
  scss:
    items:
      - scss/ei.scss:
          bundles: [home]
      - scss/figures.scss

