# Site URL

title: "Ei!"
url: "http://ekowabaka.me/ei"
description: "Ei!"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default

# menu:
#   - title: Documentation
#     url: docs/
#   - title: Code
#     url: https://github.com/ekowabaka/clearice

theme: 
    name: site
    primary-color: "#1a1a1a"
    secondary-color: "#ef870b"

plugins:
  - contrib/responsive_images

assets:
  scss:
    items:
      - scss/ei.scss:
          bundles: [home]

