# Site URL

title: "Ei!"
url: "http://ekowabaka.me/ei"
description: "Ei!"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: default

# menu:
#   - title: Documentation
#     url: docs/
#   - title: Code
#     url: https://github.com/ekowabaka/clearice

# theme: 
#     name: site
#     primary-color: "#1E212B"
#     secondary-color: "#4D8B31"

# plugins:
#   - contrib/highlight:
#       style: rainbow

# assets:
#   scss:
#     items:
#       - scss/homepage.scss:
#           priority: -1000

