# Site URL

title: "ekowabaka.me"
url: "http://ekowabaka.me/blog"
tagline: "my little space on the big web"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: blog
taxonomies: [category, tags]
menu:
  - title: "Home"
    url: "http://ekowabaka.me"
  - title: "Blog"
    url: "http://ekowabaka.me/blog"
  - title: "Projects"
    url: "http://ekowabaka.me/projects"
theme: 
  name: blog
  # primary-color: "#00a9fb"
  # secondary-color: "#a0a0a0"
plugins:
  - foonoo/highlight:
      style: a11y-light
  - foonoo/responsive_images:
      hidpi: true
      max-width: 996
      frame: figure
assets:
  css:
    items:
      - css/home.css
