# Site URL

name: "ekowabaka.me"
url: "http://ekowabaka.me/blog"
description: "There's freedom in knowledge"
author: "Ekow Abaka Ainooson <jainooson@gmail.com>"
type: blog
plugins:
  - contrib/highlight
