name: build_site
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/checkout@v2
              with:
                repository: foonoo/foonoo
                ref: dev
            - run: ~/foonoo/bin/foonoo generate -o ~/output
